# Enable or disable the automatic Git LFS tracking logic
enable_autolfs: true
# Directory where temporary session archives are stored
session_artifact_dir: "codex_sessions/"
# Any file larger than this size (in megabytes) will be moved to Git LFS
size_threshold_mb: 50
# File extensions that should always be committed via Git LFS
binary_extensions:
  - .db
  - .7z
  - .bak
  - .dot
  - .sqlite
  - .exe
  - .ttf
  - .otf
  - .woff
  - .woff2
  - .tar
  - .tgz
  - .tar.gz
  - .tbz2
  - .tar.bz2
  - .txz
  - .tar.xz
  - .tzst
  - .tar.zst
  - .rar
  - .jar
  - .war
  - .ear
  - .apk
  - .ipa
  - .nupkg
  - .cab
  - .iso
# Template used when generating .gitattributes automatically
gitattributes_template: |
  codex_sessions/*.zip filter=lfs diff=lfs merge=lfs -text
  *.db filter=lfs diff=lfs merge=lfs -text
  *.bak filter=lfs diff=lfs merge=lfs -text
  *.sqlite filter=lfs diff=lfs merge=lfs -text
  *.exe filter=lfs diff=lfs merge=lfs -text
  *.dot filter=lfs diff=lfs merge=lfs -text
  *.ttf filter=lfs diff=lfs merge=lfs -text
  *.otf filter=lfs diff=lfs merge=lfs -text
  *.woff filter=lfs diff=lfs merge=lfs -text
  *.woff2 filter=lfs diff=lfs merge=lfs -text
  # Web GUI asset binaries
  web_gui/assets/icons/** filter=lfs diff=lfs merge=lfs -text
  web_gui/assets/images/** filter=lfs diff=lfs merge=lfs -text
  web_gui/assets/fonts/** filter=lfs diff=lfs merge=lfs -text
  # BEGIN LFS ARCHIVES (autogen)
  # ZIP (case-insensitive)
  *.[zZ][iI][pP] filter=lfs diff=lfs merge=lfs -text

  # TAR family
  *.tar filter=lfs diff=lfs merge=lfs -text
  *.tgz filter=lfs diff=lfs merge=lfs -text
  *.tar.gz filter=lfs diff=lfs merge=lfs -text
  *.tbz2 filter=lfs diff=lfs merge=lfs -text
  *.tar.bz2 filter=lfs diff=lfs merge=lfs -text
  *.txz filter=lfs diff=lfs merge=lfs -text
  *.tar.xz filter=lfs diff=lfs merge=lfs -text
  *.tzst filter=lfs diff=lfs merge=lfs -text
  *.tar.zst filter=lfs diff=lfs merge=lfs -text

  # Other archive/container formats
  *.7z filter=lfs diff=lfs merge=lfs -text
  *.rar filter=lfs diff=lfs merge=lfs -text
  *.jar filter=lfs diff=lfs merge=lfs -text
  *.war filter=lfs diff=lfs merge=lfs -text
  *.ear filter=lfs diff=lfs merge=lfs -text
  *.apk filter=lfs diff=lfs merge=lfs -text
  *.ipa filter=lfs diff=lfs merge=lfs -text
  *.nupkg filter=lfs diff=lfs merge=lfs -text
  *.cab filter=lfs diff=lfs merge=lfs -text
  *.iso filter=lfs diff=lfs merge=lfs -text
  # END LFS ARCHIVES (autogen)
  # Explicit text placeholders (never LFS)
  **/.gitkeep      -filter -diff -merge text
  **/.keep         -filter -diff -merge text
  **/.placeholder  -filter -diff -merge text
