enable_autolfs: true
size_threshold_mb: 50
binary_extensions:
  - .db
  - .7z
  - .zip
  - .bak
  - .dot
  - .sqlite
  - .exe
gitattributes_template: |
  *.db filter=lfs diff=lfs merge=lfs -text
  *.7z filter=lfs diff=lfs merge=lfs -text
  *.zip filter=lfs diff=lfs merge=lfs -text
  *.bak filter=lfs diff=lfs merge=lfs -text
  *.dot filter=lfs diff=lfs merge=lfs -text
