# Auto-generated by codex_repo_maint.py
import sqlite3
from pathlib import Path

import pytest


def _minimal_create_tables(db_path: str):
    conn = sqlite3.connect(db_path)
    conn.execute("CREATE TABLE IF NOT EXISTS t(x INTEGER)")
    conn.commit()
    conn.close()


def corrupt_file(p: Path) -> None:
    p.write_bytes(b"not-a-sqlite-db")


def _ensure_func():
    try:
        from scripts.database.recovery_support import ensure_db_with_recovery
        return ensure_db_with_recovery
    except Exception:
        pytest.skip("recovery_support.ensure_db_with_recovery not available")


def test_auto_recovery_from_corrupt(tmp_path: Path) -> None:
    dbp = tmp_path / "app.db"
    corrupt_file(dbp)
    ensure = _ensure_func()
    status = ensure(str(dbp), _minimal_create_tables)
    assert status == "recreated", "DB should be recreated after corruption"


def test_integrity_ok(tmp_path: Path) -> None:
    dbp = tmp_path / "ok.db"
    _minimal_create_tables(str(dbp))
    ensure = _ensure_func()
    status = ensure(str(dbp), _minimal_create_tables)
    assert status in ("ok", "recreated")

