# Auto-generated by codex_repo_maint.py
import os
from pathlib import Path


def test_backup_root_outside_repo(tmp_path) -> None:
    repo = Path.cwd()
    val = os.environ.get("GH_COPILOT_BACKUP_ROOT")
    assert val, "GH_COPILOT_BACKUP_ROOT must be set"
    p = Path(val)
    assert repo not in p.resolve().parents and p.resolve() != repo.resolve()

