version: "3"
services:
  web:
    build: ..
    command: gunicorn app:app -c deployment/gunicorn_config.py
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
