# ENTERPRISE DOCKER COMPOSE TEMPLATE
# DUAL COPILOT: ✅ ACTIVE | Anti-Recursion: ✅ PROTECTED

version: '3.8'

services:
  {{SERVICE_NAME}}:
    image: {{DOCKER_IMAGE}}:{{IMAGE_TAG}}
    ports:
      - "{{HOST_PORT}}:{{CONTAINER_PORT}}"
    environment:
      - DATABASE_URL={{DATABASE_URL}}
      - API_KEY={{API_KEY}}
      - LOG_LEVEL={{LOG_LEVEL}}
      - ENVIRONMENT={{ENVIRONMENT_NAME}}
    volumes:
      - {{DATA_VOLUME}}:/data
      - {{LOG_VOLUME}}:/logs
    networks:
      - {{NETWORK_NAME}}

networks:
  {{NETWORK_NAME}}:
    driver: bridge
