# Auto-generated by codex_repo_maint.py
import sqlite3
from datetime import datetime
from pathlib import Path


def ensure_db_with_recovery(db_path: str, create_tables_callable):
    """Ensure a SQLite database exists; recreate if corrupted."""
    dbp = Path(db_path)
    dbp.parent.mkdir(parents=True, exist_ok=True)

    def _rename_to_corrupt(p: Path) -> Path:
        suffix = datetime.now().strftime("%Y%m%d-%H%M%S")
        cp = p.with_suffix(p.suffix + f".corrupt.{suffix}")
        if p.exists():
            p.rename(cp)
        return cp

    def _probe(conn: sqlite3.Connection) -> bool:
        try:
            try:
                cur = conn.execute("PRAGMA integrity_check")
                row = cur.fetchone()
                if row and isinstance(row[0], str) and row[0].lower() == "ok":
                    return True
            except sqlite3.DatabaseError:
                pass
            conn.execute("PRAGMA schema_version")
            return True
        except sqlite3.DatabaseError:
            return False

    try:
        conn = sqlite3.connect(str(dbp))
        ok = _probe(conn)
        conn.close()
        if not ok:
            _rename_to_corrupt(dbp)
            create_tables_callable(str(dbp))
            return "recreated"
        return "ok"
    except sqlite3.DatabaseError:
        _rename_to_corrupt(dbp)
        create_tables_callable(str(dbp))
        return "recreated"

